export const actionNames = {
    //basket constants
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
    UPDATE_ITEM_COUNT: 'UPDATE_ITEM_COUNT',

    //item's filter constants
    SET_MAX_PRICE_RANGE: 'SET MAX PRICE',
    SET_MIN_PRICE_RANGE: 'SET MIN PRICE',

    CHANGE_SELECTED_SIZE: 'CHANGE_SELECTED_SIZE',
    RESET_SELECTED_SIZES: 'RESET_SELECTED_SIZES',

    CHANGE_SELECTED_COLOR: 'CHANGE_SELECTED_COLOR',
    RESET_SELECTED_COLORS: 'RESET_SELECTED_COLORS',

    CHANGE_SELECTED_TAG: 'CHANGE_SELECTED_TAG',
    RESET_SELECTED_TAGS: 'RESET_SELECTED_TAGS',

    CHANGE_SELECTED_BRAND: 'CHANGE_SELECTED_BRAND',
    RESET_SELECTED_BRANDS: 'RESET_SELECTED_BRANDS',

    CHANGE_SELECTED_CATEGORY: 'CHANGE_SELECTED_CATEGORY',
    RESET_SELECTED_CATEGORIES: 'RESET_SELECTED_CATEGORIES',
    //products
    CHANGE_SORT_METHOD: 'CHANGE_SORT_METHOD',
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE'
};

